# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  checkout: 
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.7
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.7
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn test

  deploy_production: 
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.7
    steps:
      - run:
          name: Update APT
          command: sudo apt update
      - run:
          name: Install pip
          command: sudo apt install awscli, python-pip
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn build
      - run:
          name: Deploy to S3
          command: aws s3 sync buils/ s3://mxlabs-clinica-production --delete

workflows:
  version: 2
  build-postbuild:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - deploy_production:
          requires:
            - test
          filters:
            branches:
              only: master