# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  checkout: 
    working_directory: ~/repo
    docker:
      - image: vhuerta/circleci-node-aws:10.7
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    working_directory: ~/repo
    docker:
      - image: vhuerta/circleci-node-aws:10.7
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn test

  deploy_development: 
    working_directory: ~/repo
    docker:
      - image: vhuerta/circleci-node-aws:10.7
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: echo "HOST=odontosi-dev.mxlabs.io >> .env"
      - run: echo "REACT_APP_BASE_URL=http://odontosi-dev.mxlabs.io/ >> .env"
      - run: yarn build
      - run:
          name: Deploy to S3
          command: aws s3 sync build/ s3://odontosi-dev.mxlabs.io --delete

  deploy_production: 
    working_directory: ~/repo
    docker:
      - image: vhuerta/circleci-node-aws:10.7
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn build
      - run:
          name: Deploy to S3
          command: aws s3 sync build/ s3:/odontosi.mxlabs.io. --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - deploy_development:
          requires:
            - test
          filters:
            branches:
              only: development
      - deploy_production:
          requires:
            - test
          filters:
            branches:
              only: master